namespace: cisco_ios  # Replace with your actual namespace
name: ios_add_vlan        # Name of the collection
version: 1.0.0
readme: README.md
authors:
  - pratinporn.ik@gmail.com
description: Ansible collection for configuring VLANs on Cisco IOS devices
license:
  - MIT
tags:
  - networking
  - cisco
  - ios
dependencies: {}
repository: https://github.com/INKPTP/ansible_collections
documentation: https://github.com/INKPTP/ansible_collections/blob/main/README.md
issues: https://github.com/INKPTP/ansible_collections/issues
