namespace: cisco_ios      # Your namespace
name: ios_add_vlan         # Collection name
version: 1.0.0
readme: README.md
authors:
  - ink@gmail.com
description: Ansible collection for configuring VLANs on Cisco IOS devices
license:
  - MIT
tags:
  - networking
  - cisco
  - ios
dependencies: {}
repository: https://github.com/INKPTP/ansible_collections
documentation: https://github.com/INKPTP/ansible_collections/blob/main/README.md
issues: https://github.com/INKPTP/ansible_collections/issues

